options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'bash'
    id: 'Imprimo Helloworld'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      - echo "------------------------------------------"
        echo " Hello World!"
        echo " Y Felicidades"
        echo "------------------------------------------"